"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class PreprocessedMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class LinearQuantizationState(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CLIP_MIN_FIELD_NUMBER: builtins.int
        CLIP_MAX_FIELD_NUMBER: builtins.int
        clip_min: builtins.float
        """Value produced by quantized code 0. Inputs are clipped to this value
        before linear quantization."""
        clip_max: builtins.float
        """Value produced by the largest quantized code. Inputs are clipped to this
        value before linear quantization."""
        def __init__(
            self,
            *,
            clip_min: builtins.float = ...,
            clip_max: builtins.float = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["clip_max", b"clip_max", "clip_min", b"clip_min"]) -> None: ...

    class CentroidQuantizationState(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        BUCKET_0_VALUE_FIELD_NUMBER: builtins.int
        BUCKET_1_VALUE_FIELD_NUMBER: builtins.int
        bucket_0_value: builtins.float
        """Value produced by packed bit/code 0."""
        bucket_1_value: builtins.float
        """Value produced by packed bit/code 1."""
        def __init__(
            self,
            *,
            bucket_0_value: builtins.float = ...,
            bucket_1_value: builtins.float = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["bucket_0_value", b"bucket_0_value", "bucket_1_value", b"bucket_1_value"]) -> None: ...

    class NodeQuantizedFeatureMetadata(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        PACKED_FEATURE_KEYS_FIELD_NUMBER: builtins.int
        DEQUANTIZED_FEATURE_KEYS_FIELD_NUMBER: builtins.int
        PACKED_FEATURE_DIM_FIELD_NUMBER: builtins.int
        DEQUANTIZED_FEATURE_DIM_FIELD_NUMBER: builtins.int
        BITS_FIELD_NUMBER: builtins.int
        LINEAR_FIELD_NUMBER: builtins.int
        CENTROID_FIELD_NUMBER: builtins.int
        @property
        def packed_feature_keys(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
            """Packed uint8 fields in output TFRecords."""
        @property
        def dequantized_feature_keys(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
            """Model-visible feature names produced after dequantizing and appending."""
        packed_feature_dim: builtins.int
        """Number of uint8 columns in the packed sidecar tensor."""
        dequantized_feature_dim: builtins.int
        """Number of fp32 columns produced after unpacking/dequantizing."""
        bits: builtins.int
        """1 means centroid; 2, 4, and 8 mean linear buckets."""
        @property
        def linear(self) -> global___PreprocessedMetadata.LinearQuantizationState: ...
        @property
        def centroid(self) -> global___PreprocessedMetadata.CentroidQuantizationState: ...
        def __init__(
            self,
            *,
            packed_feature_keys: collections.abc.Iterable[builtins.str] | None = ...,
            dequantized_feature_keys: collections.abc.Iterable[builtins.str] | None = ...,
            packed_feature_dim: builtins.int = ...,
            dequantized_feature_dim: builtins.int = ...,
            bits: builtins.int = ...,
            linear: global___PreprocessedMetadata.LinearQuantizationState | None = ...,
            centroid: global___PreprocessedMetadata.CentroidQuantizationState | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["centroid", b"centroid", "linear", b"linear"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["bits", b"bits", "centroid", b"centroid", "dequantized_feature_dim", b"dequantized_feature_dim", "dequantized_feature_keys", b"dequantized_feature_keys", "linear", b"linear", "packed_feature_dim", b"packed_feature_dim", "packed_feature_keys", b"packed_feature_keys"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["state", b"state"]) -> typing_extensions.Literal["linear", "centroid"] | None: ...

    class NodeMetadataOutput(google.protobuf.message.Message):
        """Houses metadata about node TFTransform output from DataPreprocessor."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NODE_ID_KEY_FIELD_NUMBER: builtins.int
        FEATURE_KEYS_FIELD_NUMBER: builtins.int
        LABEL_KEYS_FIELD_NUMBER: builtins.int
        TFRECORD_URI_PREFIX_FIELD_NUMBER: builtins.int
        SCHEMA_URI_FIELD_NUMBER: builtins.int
        ENUMERATED_NODE_IDS_BQ_TABLE_FIELD_NUMBER: builtins.int
        ENUMERATED_NODE_DATA_BQ_TABLE_FIELD_NUMBER: builtins.int
        FEATURE_DIM_FIELD_NUMBER: builtins.int
        TRANSFORM_FN_ASSETS_URI_FIELD_NUMBER: builtins.int
        QUANTIZED_FEATURE_METADATA_FIELD_NUMBER: builtins.int
        node_id_key: builtins.str
        """The field in output TFRecords which references the node identifier."""
        @property
        def feature_keys(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
            """Fields in output TFRecords which reference features."""
        @property
        def label_keys(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
            """Fields in output TFRecords which reference labels."""
        tfrecord_uri_prefix: builtins.str
        """GCS prefix which can be used to glob the TFRecord dataset."""
        schema_uri: builtins.str
        """GCS path to a schema which can be used to parse the TFRecord dataset."""
        enumerated_node_ids_bq_table: builtins.str
        """BQ path to a table which stores the original to enumerated node id association."""
        enumerated_node_data_bq_table: builtins.str
        """BQ path to a table which stores the enumerated node id to node metadata association."""
        feature_dim: builtins.int
        """Feature dimension after preprocessing"""
        transform_fn_assets_uri: builtins.str
        """Contains categorical feature vocabularies"""
        @property
        def quantized_feature_metadata(self) -> global___PreprocessedMetadata.NodeQuantizedFeatureMetadata:
            """Optional append-only quantized node feature sidecar metadata."""
        def __init__(
            self,
            *,
            node_id_key: builtins.str = ...,
            feature_keys: collections.abc.Iterable[builtins.str] | None = ...,
            label_keys: collections.abc.Iterable[builtins.str] | None = ...,
            tfrecord_uri_prefix: builtins.str = ...,
            schema_uri: builtins.str = ...,
            enumerated_node_ids_bq_table: builtins.str = ...,
            enumerated_node_data_bq_table: builtins.str = ...,
            feature_dim: builtins.int | None = ...,
            transform_fn_assets_uri: builtins.str = ...,
            quantized_feature_metadata: global___PreprocessedMetadata.NodeQuantizedFeatureMetadata | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["_feature_dim", b"_feature_dim", "feature_dim", b"feature_dim", "quantized_feature_metadata", b"quantized_feature_metadata"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["_feature_dim", b"_feature_dim", "enumerated_node_data_bq_table", b"enumerated_node_data_bq_table", "enumerated_node_ids_bq_table", b"enumerated_node_ids_bq_table", "feature_dim", b"feature_dim", "feature_keys", b"feature_keys", "label_keys", b"label_keys", "node_id_key", b"node_id_key", "quantized_feature_metadata", b"quantized_feature_metadata", "schema_uri", b"schema_uri", "tfrecord_uri_prefix", b"tfrecord_uri_prefix", "transform_fn_assets_uri", b"transform_fn_assets_uri"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["_feature_dim", b"_feature_dim"]) -> typing_extensions.Literal["feature_dim"] | None: ...

    class EdgeMetadataInfo(google.protobuf.message.Message):
        """Houses metadata of edge features output from DataPreprocessor"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        FEATURE_KEYS_FIELD_NUMBER: builtins.int
        LABEL_KEYS_FIELD_NUMBER: builtins.int
        TFRECORD_URI_PREFIX_FIELD_NUMBER: builtins.int
        SCHEMA_URI_FIELD_NUMBER: builtins.int
        ENUMERATED_EDGE_DATA_BQ_TABLE_FIELD_NUMBER: builtins.int
        FEATURE_DIM_FIELD_NUMBER: builtins.int
        TRANSFORM_FN_ASSETS_URI_FIELD_NUMBER: builtins.int
        @property
        def feature_keys(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
            """Fields in output TFRecords which reference features."""
        @property
        def label_keys(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
            """Fields in output TFRecords which reference labels."""
        tfrecord_uri_prefix: builtins.str
        """GCS prefix which can be used to glob the TFRecord dataset."""
        schema_uri: builtins.str
        """GCS path to a schema which can be used to parse the TFRecord dataset."""
        enumerated_edge_data_bq_table: builtins.str
        """BQ path to a table which stores the enumerated node id to node metadata association."""
        feature_dim: builtins.int
        """Feature dimension after preprocessing"""
        transform_fn_assets_uri: builtins.str
        """Contains categorical feature vocabularies"""
        def __init__(
            self,
            *,
            feature_keys: collections.abc.Iterable[builtins.str] | None = ...,
            label_keys: collections.abc.Iterable[builtins.str] | None = ...,
            tfrecord_uri_prefix: builtins.str = ...,
            schema_uri: builtins.str = ...,
            enumerated_edge_data_bq_table: builtins.str = ...,
            feature_dim: builtins.int | None = ...,
            transform_fn_assets_uri: builtins.str = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["_feature_dim", b"_feature_dim", "feature_dim", b"feature_dim"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["_feature_dim", b"_feature_dim", "enumerated_edge_data_bq_table", b"enumerated_edge_data_bq_table", "feature_dim", b"feature_dim", "feature_keys", b"feature_keys", "label_keys", b"label_keys", "schema_uri", b"schema_uri", "tfrecord_uri_prefix", b"tfrecord_uri_prefix", "transform_fn_assets_uri", b"transform_fn_assets_uri"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["_feature_dim", b"_feature_dim"]) -> typing_extensions.Literal["feature_dim"] | None: ...

    class EdgeMetadataOutput(google.protobuf.message.Message):
        """Houses metadata about edge TFTransform output from DataPreprocessor."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SRC_NODE_ID_KEY_FIELD_NUMBER: builtins.int
        DST_NODE_ID_KEY_FIELD_NUMBER: builtins.int
        MAIN_EDGE_INFO_FIELD_NUMBER: builtins.int
        POSITIVE_EDGE_INFO_FIELD_NUMBER: builtins.int
        NEGATIVE_EDGE_INFO_FIELD_NUMBER: builtins.int
        src_node_id_key: builtins.str
        """The field in output TFRecords which references the source node identifier."""
        dst_node_id_key: builtins.str
        """The field in output TFRecords which references the destination node identifier."""
        @property
        def main_edge_info(self) -> global___PreprocessedMetadata.EdgeMetadataInfo:
            """Detailed metadata for message-passing edges"""
        @property
        def positive_edge_info(self) -> global___PreprocessedMetadata.EdgeMetadataInfo:
            """Detailed metadata for user-defined positive edges"""
        @property
        def negative_edge_info(self) -> global___PreprocessedMetadata.EdgeMetadataInfo:
            """Detailed metadata for user-defined negative edges"""
        def __init__(
            self,
            *,
            src_node_id_key: builtins.str = ...,
            dst_node_id_key: builtins.str = ...,
            main_edge_info: global___PreprocessedMetadata.EdgeMetadataInfo | None = ...,
            positive_edge_info: global___PreprocessedMetadata.EdgeMetadataInfo | None = ...,
            negative_edge_info: global___PreprocessedMetadata.EdgeMetadataInfo | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["_negative_edge_info", b"_negative_edge_info", "_positive_edge_info", b"_positive_edge_info", "main_edge_info", b"main_edge_info", "negative_edge_info", b"negative_edge_info", "positive_edge_info", b"positive_edge_info"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["_negative_edge_info", b"_negative_edge_info", "_positive_edge_info", b"_positive_edge_info", "dst_node_id_key", b"dst_node_id_key", "main_edge_info", b"main_edge_info", "negative_edge_info", b"negative_edge_info", "positive_edge_info", b"positive_edge_info", "src_node_id_key", b"src_node_id_key"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing_extensions.Literal["_negative_edge_info", b"_negative_edge_info"]) -> typing_extensions.Literal["negative_edge_info"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing_extensions.Literal["_positive_edge_info", b"_positive_edge_info"]) -> typing_extensions.Literal["positive_edge_info"] | None: ...

    class CondensedNodeTypeToPreprocessedMetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> global___PreprocessedMetadata.NodeMetadataOutput: ...
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: global___PreprocessedMetadata.NodeMetadataOutput | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    class CondensedEdgeTypeToPreprocessedMetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> global___PreprocessedMetadata.EdgeMetadataOutput: ...
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: global___PreprocessedMetadata.EdgeMetadataOutput | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    CONDENSED_NODE_TYPE_TO_PREPROCESSED_METADATA_FIELD_NUMBER: builtins.int
    CONDENSED_EDGE_TYPE_TO_PREPROCESSED_METADATA_FIELD_NUMBER: builtins.int
    @property
    def condensed_node_type_to_preprocessed_metadata(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___PreprocessedMetadata.NodeMetadataOutput]:
        """Maps condensed node types to their respective post-TFTransform outputs."""
    @property
    def condensed_edge_type_to_preprocessed_metadata(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___PreprocessedMetadata.EdgeMetadataOutput]:
        """Maps condensed edge types to their respective post-TFTransform outputs."""
    def __init__(
        self,
        *,
        condensed_node_type_to_preprocessed_metadata: collections.abc.Mapping[builtins.int, global___PreprocessedMetadata.NodeMetadataOutput] | None = ...,
        condensed_edge_type_to_preprocessed_metadata: collections.abc.Mapping[builtins.int, global___PreprocessedMetadata.EdgeMetadataOutput] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["condensed_edge_type_to_preprocessed_metadata", b"condensed_edge_type_to_preprocessed_metadata", "condensed_node_type_to_preprocessed_metadata", b"condensed_node_type_to_preprocessed_metadata"]) -> None: ...

global___PreprocessedMetadata = PreprocessedMetadata
