max_steps: 10000
dataloader:
  num_workers: 4
sampling:
  positive_edge_batch_size: 256
  num_inbatch_negatives_per_edge: 0
  num_random_negatives_per_edge: 16
  negative_corruption_side: DST
optimizer:
  sparse:
    lr: 0.001
    weight_decay: 0.001
  dense:
    lr: 0.001
    weight_decay: 0.001
distributed:
  num_processes_per_machine: 4
  storage_reservation_percentage: 0.15
checkpointing:
  save_every: 500
  should_save_async: false
  save_to_path: /tmp/kge_checkpoints
logging:
  log_every: 1
