graphMetadata:
  # We have 3 nodes types in the DBLP Dataset: author, paper, and term. We also have 3
  # edge types: author -> paper, paper -> author, and term -> paper
  edgeTypes:
  - dstNodeType: paper
    relation: to
    srcNodeType: author
  - dstNodeType: author
    relation: to
    srcNodeType: paper
  - dstNodeType: paper
    relation: to
    srcNodeType: term
  nodeTypes:
  - author
  - paper
  - term
taskMetadata:
  nodeAnchorBasedLinkPredictionTaskMetadata:
    # We aim to predict paper -> author links in the graph.
    supervisionEdgeTypes:
    - dstNodeType: author
      relation: to
      srcNodeType: paper
datasetConfig:
  dataPreprocessorConfig:
    dataPreprocessorConfigClsPath: gigl.src.mocking.mocking_assets.passthrough_preprocessor_config_for_mocked_assets.PassthroughPreprocessorConfigForMockedAssets
    dataPreprocessorArgs:
      # This argument is specific for the `PassthroughPreprocessorConfigForMockedAssets` preprocessor to indicate which dataset we should be using
      mocked_dataset_name: 'dblp_node_anchor_edge_features_lp'
inferencerConfig:
  inferencerArgs:
    # Example argument to inferencer
    log_every_n_batch: "50"
  inferenceBatchSize: 512
  command: python -m examples.distributed.heterogeneous_inference
sharedConfig:
  shouldSkipAutomaticTempAssetCleanup: false
  shouldSkipInference: false
  shouldSkipTraining: true  # Live subgraph sampling pipelines do not have a training phase that is being tested right now
  shouldSkipModelEvaluation: true
  trainedModelMetadata:
    # This is an example model trained on the DBLP dataset. To train a custom DBLP model, please refer to the
    # `gigl/src/mocking/configs/dblp_node_anchor_based_link_prediction_template_gbml_config.yaml` config template.
    # You can run a pipeline for training on DBLP using `make run_dblp_nalp_e2e_kfp_test`.
    trainedModelUri: gs://public-gigl/mocked_assets/2024-08-01--17-11-27-UTC/dblp_node_anchor_edge_features_lp/trainer/models/model.pt
featureFlags:
  should_run_glt_backend: 'True'
