datasetConfig:
  dataPreprocessorConfig:
    dataPreprocessorArgs:
      mocked_dataset_name: cora_homogeneous_node_anchor_edge_features_user_defined_labels
    dataPreprocessorConfigClsPath: gigl.src.mocking.mocking_assets.passthrough_preprocessor_config_for_mocked_assets.PassthroughPreprocessorConfigForMockedAssets
  splitGeneratorConfig:
    assignerArgs:
      seed: '42'
      test_split: '0.2'
      train_split: '0.7'
      val_split: '0.1'
    assignerClsPath: splitgenerator.lib.assigners.UserDefinedLabelsEdgeToLinkSplitHashingAssigner
    splitStrategyClsPath: splitgenerator.lib.split_strategies.UserDefinedLabelsNodeAnchorBasedLinkPredictionSplitStrategy
  subgraphSamplerConfig:
    numHops: 2
    numNeighborsToSample: 10
    numUserDefinedNegativeSamples: 1
    numUserDefinedPositiveSamples: 1
featureFlags:
  data_preprocessor_num_shards: '2'
  should_run_glt_backend: 'True'
graphMetadata:
  condensedEdgeTypeMap:
    '0':
      dstNodeType: paper
      relation: cites
      srcNodeType: paper
  condensedNodeTypeMap:
    '0': paper
  edgeTypes:
  - dstNodeType: paper
    relation: cites
    srcNodeType: paper
  nodeTypes:
  - paper
inferencerConfig:
  command: python -m examples.distributed.homogeneous_inference
  inferenceBatchSize: 512
  inferencerArgs:
    log_every_n_batch: '50'
sharedConfig:
  datasetMetadata:
    nodeAnchorBasedLinkPredictionDataset:
      testMainDataUri: gs://gigl-cicd-perm/cora_glt_udl_test_on__54606/split_generator/test/main_samples/samples/
      testNodeTypeToRandomNegativeDataUri:
        paper: gs://gigl-cicd-perm/cora_glt_udl_test_on__54606/split_generator/test/random_negatives/paper/neighborhoods/
      trainMainDataUri: gs://gigl-cicd-perm/cora_glt_udl_test_on__54606/split_generator/train/main_samples/samples/
      trainNodeTypeToRandomNegativeDataUri:
        paper: gs://gigl-cicd-perm/cora_glt_udl_test_on__54606/split_generator/train/random_negatives/paper/neighborhoods/
      valMainDataUri: gs://gigl-cicd-perm/cora_glt_udl_test_on__54606/split_generator/val/main_samples/samples/
      valNodeTypeToRandomNegativeDataUri:
        paper: gs://gigl-cicd-perm/cora_glt_udl_test_on__54606/split_generator/val/random_negatives/paper/neighborhoods/
  flattenedGraphMetadata:
    nodeAnchorBasedLinkPredictionOutput:
      nodeTypeToRandomNegativeTfrecordUriPrefix:
        paper: gs://gigl-cicd-perm/cora_glt_udl_test_on__54606/subgraph_sampler/node_anchor_based_link_prediction/random_negative_rooted_neighborhood_samples/paper/samples/
      tfrecordUriPrefix: gs://gigl-cicd-perm/cora_glt_udl_test_on__54606/subgraph_sampler/node_anchor_based_link_prediction/node_anchor_based_link_prediction_samples/samples/
  inferenceMetadata:
    nodeTypeToInferencerOutputInfoMap:
      paper:
        embeddingsPath: external-snap-ci-github-gigl.gigl_embeddings.embeddings_paper_cora_glt_udl_test_on__54606
  postprocessedMetadata:
    postProcessorLogMetricsUri: gs://gigl-cicd-perm/cora_glt_udl_test_on__54606/post_processor/post_processor_metrics.json
  preprocessedMetadataUri: gs://gigl-cicd-perm/cora_glt_udl_test_on__54606/data_preprocess/preprocessed_metadata.yaml
  shouldSkipModelEvaluation: true
  shouldSkipTraining: true
  trainedModelMetadata:
    evalMetricsUri: gs://gigl-cicd-perm/cora_glt_udl_test_on__54606/trainer/models/trainer_eval_metrics.json
    scriptedModelUri: gs://gigl-cicd-perm/cora_glt_udl_test_on__54606/trainer/models/scripted_model.pt
    tensorboardLogsUri: gs://gigl-cicd-perm/cora_glt_udl_test_on__54606/trainer/tensorboard_logs/
    trainedModelUri: gs://public-gigl/mocked_assets/2024-07-15--21-30-07-UTC/cora_homogeneous_node_anchor_edge_features_user_defined_labels/trainer/models/model.pt
taskMetadata:
  nodeAnchorBasedLinkPredictionTaskMetadata:
    supervisionEdgeTypes:
    - dstNodeType: paper
      relation: cites
      srcNodeType: paper
