substitutions:
  _CMD: ""
options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: us-central1-docker.pkg.dev/external-snap-ci-github-gigl/gigl-base-images/gigl-builder:63cb24986b4af3d368e9a9b1ba205e06c43b37d0.34.1
    entrypoint: /bin/bash
    args:
      - -c
      - |
        set -e
        set -x

        if [[ -z "${_CMD}" ]]; then
          echo "Error: _CMD is not set."
          exit 1
        fi

        echo "Setting up environment..."
        # gcloud runner will run as a non-root user, but all paths/profiles, etc are set up for root
        echo "source /root/.bashrc" >> ~/.bashrc
        echo "source /root/.profile" >> ~/.profile

        source ~/.profile
        docker buildx create --driver=docker-container --use
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        gcloud auth configure-docker us-central1-docker.pkg.dev
        # Install GiGL
        pip install -e ./python/
        # The builder operates in its own user dir, usually /workspace,
        # so we need to copy the gigl tools dir to the current cloud_builder's user dir.
        # See: containers/Dockerfile.builder.
        # We cannot just symlink as that causes issues when trying to build the
        # dev workbench image i.e. symlinked sub dirs are not copied over.
        # See: containers/Dockerfile.gigl_workbench_container
        cp -rf /gigl_deps/tools/ tools

        echo "Finished setting up environment."
        echo "========================="
        echo "Running command: ${_CMD}"
        echo "========================="
        $_CMD
        echo "Finished running command"
