substitutions:
  _CMD: ""
options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: us-central1-docker.pkg.dev/external-snap-ci-github-gigl/gigl-base-images/gigl-builder:59e780eeb5831d4ce75747262b8e57b46f3dc17a.24.1
    entrypoint: /bin/bash
    args:
      - -c
      - |
        set -e
        set -x

        if [[ -z "${_CMD}" ]]; then
          echo "Error: _CMD is not set."
          exit 1
        fi

        echo "Setting up environment..."
        docker buildx create --driver=docker-container --use
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        gcloud auth configure-docker us-central1-docker.pkg.dev

        # TODO: (svij) Enable install_scala_deps.sh to inside Docker image build
        bash ./requirements/install_scala_deps.sh
        pip install -e ./python/

        echo "Finished setting up environment."
        echo "========================="
        echo "Running command: ${_CMD}"
        echo "========================="
        $_CMD
        echo "Finished running command"
