// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package snapchat.research.gbml.gigl_resource_config

/** Reservation affinity for a Vertex AI job.
  * Maps to google.cloud.aiplatform_v1.types.ReservationAffinity.
  * See https://docs.cloud.google.com/vertex-ai/docs/training/use-reservations
  *
  * @param type
  *   One of "NO_RESERVATION", "ANY_RESERVATION", "SPECIFIC_RESERVATION".
  *   Unset/empty means no reservation_affinity is set on the MachineSpec and
  *   Vertex AI applies its own default behavior.
  *   Note: "TYPE_UNSPECIFIED" is rejected by the validator; use the empty
  *   string for "no preference".
  * @param reservationResourceNames
  *   Full resource names of reservations to consume.
  *   Required when type == "SPECIFIC_RESERVATION"; must be empty otherwise.
  *   Format: projects/{project}/zones/{zone}/reservations/{reservation_name}
  */
@SerialVersionUID(0L)
final case class VertexAiReservationAffinity(
    `type`: _root_.scala.Predef.String = "",
    reservationResourceNames: _root_.scala.Seq[_root_.scala.Predef.String] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[VertexAiReservationAffinity] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0

      {
        val __value = `type`
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      reservationResourceNames.foreach { __item =>
        val __value = __item
        __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1

    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = `type`
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      reservationResourceNames.foreach { __v =>
        val __m = __v
        _output__.writeString(2, __m)
      };
      unknownFields.writeTo(_output__)
    }
    def withType(__v: _root_.scala.Predef.String): VertexAiReservationAffinity = copy(`type` = __v)
    def clearReservationResourceNames = copy(reservationResourceNames = _root_.scala.Seq.empty)
    def addReservationResourceNames(__vs: _root_.scala.Predef.String *): VertexAiReservationAffinity = addAllReservationResourceNames(__vs)
    def addAllReservationResourceNames(__vs: Iterable[_root_.scala.Predef.String]): VertexAiReservationAffinity = copy(reservationResourceNames = reservationResourceNames ++ __vs)
    def withReservationResourceNames(__v: _root_.scala.Seq[_root_.scala.Predef.String]): VertexAiReservationAffinity = copy(reservationResourceNames = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = `type`
          if (__t != "") __t else null
        }
        case 2 => reservationResourceNames
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(`type`)
        case 2 => _root_.scalapb.descriptors.PRepeated(reservationResourceNames.iterator.map(_root_.scalapb.descriptors.PString(_)).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: snapchat.research.gbml.gigl_resource_config.VertexAiReservationAffinity.type = snapchat.research.gbml.gigl_resource_config.VertexAiReservationAffinity
    // @@protoc_insertion_point(GeneratedMessage[snapchat.research.gbml.VertexAiReservationAffinity])
}

object VertexAiReservationAffinity extends scalapb.GeneratedMessageCompanion[snapchat.research.gbml.gigl_resource_config.VertexAiReservationAffinity] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[snapchat.research.gbml.gigl_resource_config.VertexAiReservationAffinity] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): snapchat.research.gbml.gigl_resource_config.VertexAiReservationAffinity = {
    var __type: _root_.scala.Predef.String = ""
    val __reservationResourceNames: _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String] = new _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Predef.String]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __type = _input__.readStringRequireUtf8()
        case 18 =>
          __reservationResourceNames += _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    snapchat.research.gbml.gigl_resource_config.VertexAiReservationAffinity(
        `type` = __type,
        reservationResourceNames = __reservationResourceNames.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[snapchat.research.gbml.gigl_resource_config.VertexAiReservationAffinity] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      snapchat.research.gbml.gigl_resource_config.VertexAiReservationAffinity(
        `type` = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        reservationResourceNames = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Seq[_root_.scala.Predef.String]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = GiglResourceConfigProto.javaDescriptor.getMessageTypes().get(6)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = GiglResourceConfigProto.scalaDescriptor.messages(6)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = snapchat.research.gbml.gigl_resource_config.VertexAiReservationAffinity(
    `type` = "",
    reservationResourceNames = _root_.scala.Seq.empty
  )
  implicit class VertexAiReservationAffinityLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, snapchat.research.gbml.gigl_resource_config.VertexAiReservationAffinity]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, snapchat.research.gbml.gigl_resource_config.VertexAiReservationAffinity](_l) {
    def `type`: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.`type`)((c_, f_) => c_.copy(`type` = f_))
    def reservationResourceNames: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Predef.String]] = field(_.reservationResourceNames)((c_, f_) => c_.copy(reservationResourceNames = f_))
  }
  final val TYPE_FIELD_NUMBER = 1
  final val RESERVATION_RESOURCE_NAMES_FIELD_NUMBER = 2
  def of(
    `type`: _root_.scala.Predef.String,
    reservationResourceNames: _root_.scala.Seq[_root_.scala.Predef.String]
  ): _root_.snapchat.research.gbml.gigl_resource_config.VertexAiReservationAffinity = _root_.snapchat.research.gbml.gigl_resource_config.VertexAiReservationAffinity(
    `type`,
    reservationResourceNames
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[snapchat.research.gbml.VertexAiReservationAffinity])
}
