dataloader:
  num_workers: 1               # Number of worker processes for validation data loading
step_frequency: 100            # Run validation every N training steps
num_batches: 10                # Maximum batches to evaluate (subset for faster validation)
sampling:
  positive_edge_batch_size: 256    # Number of positive edges per validation batch
  num_random_negatives_per_edge: 100  # Random negative samples per edge for ranking
  num_inbatch_negatives_per_edge: 0   # In-batch negatives (not used in validation)
  negative_corruption_side: DST       # Corrupt destination nodes for negative sampling
