metadata:  # The yaml corresponding to the GraphMetadata protobuf.
  node_types:
    - paper
  edge_types:
    - dst_node_type: paper
      relation: cites
      src_node_type: paper
  condensed_edge_type_map:
    0:
      dst_node_type: paper
      relation: cites
      src_node_type: paper
  condensed_node_type_map:
    0: paper

raw_graph_data:
  node_data:
    - _target_: gigl.src.data_preprocessor.lib.ingest.bigquery.BigqueryNodeDataReference
      node_type: paper
      reference_uri: external-snap-ci-github-gigl.public_gigl.cora_homogeneous_node_anchor_edge_features_paper_nodes_2025-07-24--18-12-02-UTC
      identifier: node_id
  edge_data:
    - _target_: gigl.src.data_preprocessor.lib.ingest.bigquery.BigqueryEdgeDataReference
      edge_type:
        _target_: gigl.src.common.types.graph_data.EdgeType
        src_node_type: paper
        relation: cites
        dst_node_type: paper
      reference_uri: external-snap-ci-github-gigl.public_gigl.cora_homogeneous_node_anchor_edge_features_paper-cites-paper_edges_main_2025-07-24--18-12-02-UTC
      src_identifier: src
      dst_identifier: dst
