"""Generate .cache/compile_commands.json for clangd.

Delegates to CMake (which already knows all include paths and compiler flags via
find_package(Torch)) rather than manually constructing the database.

CMake is configured with clang++-15 directly so clangd natively understands the
commands without needing a ``--query-driver`` workaround. This cmake invocation
is only for generating compile_commands.json — the actual extension build (via
``uv pip install -e gigl-core/``) uses the system default compiler independently.

Primary use: called by ``run_cpp_lint.py`` before running clangd checks, and
by ``make generate_compile_commands`` when you need to refresh the database
manually (e.g. after adding new source files or changing compiler flags).

Usage::

    make generate_compile_commands
"""

import subprocess
from pathlib import Path

_REPO_ROOT: Path = Path(__file__).resolve().parent.parent
_GIGL_CORE_DIR: Path = _REPO_ROOT / "gigl-core"
# CMakeInit.txt is generated by scikit-build-core during `uv pip install -e gigl-core/`.
# It sets CMAKE_PREFIX_PATH to the environment's site-packages so CMake can find
# pybind11 and torch. Must exist before this script is called (run build_cpp_extensions).
_GIGL_CORE_CMAKE_INIT: Path = (
    _GIGL_CORE_DIR / ".cache" / "cmake_build" / "CMakeInit.txt"
)
_CMAKE_BUILD_DIR: Path = _REPO_ROOT / ".cache" / "cmake_build_lint"
COMPILE_COMMANDS: Path = _REPO_ROOT / ".cache" / "compile_commands.json"


def write_compile_commands() -> None:
    """Run CMake to generate .cache/compile_commands.json.

    Configures gigl-core's CMakeLists.txt with clang++-15, loading
    ``gigl-core/.cache/cmake_build/CMakeInit.txt`` (written by
    ``uv pip install -e gigl-core/``) for the correct ``CMAKE_PREFIX_PATH``.
    """
    if not _GIGL_CORE_CMAKE_INIT.exists():
        raise FileNotFoundError(
            f"{_GIGL_CORE_CMAKE_INIT} not found. "
            "Run `make build_cpp_extensions` first to generate it."
        )
    _CMAKE_BUILD_DIR.mkdir(parents=True, exist_ok=True)
    result = subprocess.run(
        [
            "cmake",
            "-C",
            str(_GIGL_CORE_CMAKE_INIT),
            "-S",
            str(_GIGL_CORE_DIR),
            "-B",
            str(_CMAKE_BUILD_DIR),
            "-DCMAKE_CXX_COMPILER=clang++-15",
            "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"CMake configure failed (exit {result.returncode}):\n{result.stderr}"
        )

    raw_path = _CMAKE_BUILD_DIR / "compile_commands.json"
    COMPILE_COMMANDS.write_text(raw_path.read_text())


def main() -> None:
    write_compile_commands()
    print(f"Wrote {COMPILE_COMMANDS}")


if __name__ == "__main__":
    main()
