# Diffs from e2e_glt_resource_config.yaml
# - Swap vertex_ai_inferencer_config for vertex_ai_graph_store_inferencer_config
# - Swap vertex_ai_trainer_config for vertex_ai_graph_store_trainer_config
defaults:
  - e2e/shared@shared_resource_config
  - e2e/preprocessor@preprocessor_config
  - _self_

trainer_resource_config:
  vertex_ai_graph_store_trainer_config:
    graph_store_pool:
      machine_type: n2-highmem-32
      gpu_type: ACCELERATOR_TYPE_UNSPECIFIED
      gpu_limit: 0
      num_replicas: 2
    compute_pool:
      machine_type: n1-standard-16
      gpu_type: NVIDIA_TESLA_T4
      gpu_limit: 2
      num_replicas: 2
inferencer_resource_config:
  vertex_ai_graph_store_inferencer_config:
    graph_store_pool:
      machine_type: n2-highmem-32
      gpu_type: ACCELERATOR_TYPE_UNSPECIFIED
      gpu_limit: 0
      num_replicas: 2
    compute_pool:
      machine_type: n1-standard-16
      gpu_type: NVIDIA_TESLA_T4
      gpu_limit: 2
      num_replicas: 2
