# GiglResourceConfig for our e2e intergration tests.
defaults:
  - e2e/shared@shared_resource_config
  - e2e/preprocessor@preprocessor_config
  - _self_

subgraph_sampler_config:
  machine_type: "n2-highmem-16"
  num_local_ssds: 2
  num_replicas: 4
split_generator_config:
  machine_type: n2-standard-16
  num_local_ssds: 2
  num_replicas: 4
trainer_config:
  vertex_ai_trainer_config:
    machine_type: "n1-highmem-8" # set to `ACCELERATOR_TYPE_UNSPECIFIED` for cpu training
    gpu_type: NVIDIA_TESLA_T4
    gpu_limit: 1  # set to 0 for cpu training
    num_replicas: 2
inferencer_config:
  num_workers: 1
  max_num_workers: 256
  machine_type: "c2d-highmem-32"
  disk_size_gb: 100
