defaults:
  - e2e/shared@shared_resource_config
  - e2e/preprocessor@preprocessor_config
  - _self_

trainer_resource_config:
  vertex_ai_trainer_config:
    machine_type: n1-highmem-32
    gpu_type: NVIDIA_TESLA_T4
    gpu_limit: 2
    num_replicas: 2
inferencer_resource_config:
  vertex_ai_inferencer_config:
    machine_type: n1-highmem-32
    gpu_type: NVIDIA_TESLA_T4
    gpu_limit: 2
    num_replicas: 2
