name: "Commit and Push Changes"
description: "Commits and pushes changes with a customizable commit message"
inputs:
  commit_message:
    description: "Commit message for the changes"
    required: true
    default: "Updated files via GitHub Actions"
  github_token:
    description: "GitHub token to authenticate and push the changes"
    required: true
  to_new_branch_named:
    description: "Create a new branch and push the changes to it"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Commit and push changes
      env:
        COMMIT_MESSAGE: ${{ inputs.commit_message }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        TO_NEW_BRANCH_NAMED: ${{ inputs.to_new_branch_named }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        if [ "$TO_NEW_BRANCH_NAMED" != "false" ]; then
          echo "Creating a new branch, named $TO_NEW_BRANCH_NAMED, and pushing the changes to it"
          git checkout -b $TO_NEW_BRANCH_NAMED
        fi

        git add .
        # Check if there are any changes
        if [ "$TO_NEW_BRANCH_NAMED" == "false" ]; then
          if git diff --cached --exit-code; then
            echo "No changes to commit."
            exit 0
          fi
        fi

        git commit -m "$COMMIT_MESSAGE"
        git push
      shell: bash
