DATE:=$(shell /bin/date "+%Y%m%d_%H%M")
PROJECT?=external-snap-ci-github-gigl

DOCKER_ARTIFACT_REGISTRY?=us-central1-docker.pkg.dev/${PROJECT}/gigl-base-images

# TODO: Make this work in future PRs; stubbing for now.
run_api_test:
	echo "TODO"
